#!/bin/bash
#
#
javac -d build/ src/IP_Complex.java src/CPLX_Utils/CPLX_NET.java
cd build
jar cfm build/[Build]IP_Complex.jar /workspaces/IP_Complex/MANIFEST.MF IP_Complex.class CPLX_Utils/CPLX_NET.class

java -jar build/[Build]IP_Complex.jar
